# frozen_string_literal: true

require 'dotenv/load'
require 'simplecov'
require 'codecov'
require 'vcr'
require 'bundler/setup'
require 'fileutils'
require 'webmock/rspec'
require 'active_support'
require 'active_support/core_ext'
require_relative 'support/simplecov_configuration'
require 'studio'
require_relative 'support/rspec_configuration'
require_relative 'support/studio_configuration'
require_relative 'support/vcr_configuration'
require_relative 'support/models_to_test'
